baseURL = "http://dshimy.dev/"
languageCode = "en-us"
title = "dshimy.dev"
theme = "sport"

[markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
  tabWidth = 2
