name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build and Deploy
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.68.3
          TARGET_REPO: dshimy/dshimy.github.io
          TOKEN: ${{ secrets.BUILD_TOKEN }}
          CNAME: dshimy.dev
